= 2022-2 객체지향프로그래밍
202103411 컴퓨터공학부 채준영

== 설명
특정한 형식으로 저장된 한류에 관련된 정보(hallyu.txt)가 저장된 txt파일의 경로를 입력하면 해당 텍스트 파일을 읽고 파싱한다.

이후, 각 제목들에 해당하는 내용들을 따로 볼 수 있으며 그 부분을 따로 폴더 경로를 지정하여 텍스트파일로 저장할 수 있다.

==============
실행예시
[source]
----
파일 경로를 입력해주세요: (파일경로)
--------------------------------------------------------
1. 파싱한 제목들 출력
2. 제목 번호를 사용하여 내용 출력
3. 제목 번호를 사용하여 내용 저장
4. 종료
원하는 작업에 해당하는 번호를 입력해주세요: 3
제목 번호를 입력해주세요: 2
저장 폴더 경로를 입력해주세요: (폴더경로)
저장되었습니다.
--------------------------------------------------------
--------------------------------------------------------
1. 파싱한 제목들 출력
2. 제목 번호를 사용하여 내용 출력
3. 제목 번호를 사용하여 내용 저장
4. 종료
원하는 작업에 해당하는 번호를 입력해주세요: 4
--------------------------------------------------------
----
==============

== 폴더 구조
src/Enum: 열거타입 파일들, 파일 이름들이 E로 시작함

src/Interface: 인터페이스 파일들, 파일 이름들이 I로 시작함

src: 자바파일들

hallyu.txt: 한류 관련 정보 파일

설명영상.mp4: 설명영상 파일

== 평가항목별 사용현황

* [*] 과제 설명 및 각 항목별 주석 작성
* [*] 클래스 상속: FileParser.java
* [*] 인터페이스: Interface/IFileParser.java, Interface/ITextParser.java
* [*] 예외 처리: App.java, TextParser.java
* [*] 다형성 (상속 / 인터페이스): FileParser.java, TextParser.java
* [*] 참조 타입 (배열 / 열거타입): Enum/EChar.java, App.java, TextParser.java
* [*] 컬렉션 프레임워크: Interface/ITextParser.java, TextParser.java
* [*] 파일 입/출력 사용: TextParser.java
* [*] 과제 설명 동영상(5분 내외): 설명영상.mp4

== hallyu.txt
나무위키 문서를 정리한 한류 관련 텍스트 파일

https://namu.wiki/w/%EA%B5%AD%EA%B0%80%EB%B3%84%20%ED%95%9C%EB%A5%98[국가별 한류]
https://namu.wiki/w/%EB%8F%99%EC%95%84%EC%8B%9C%EC%95%84%EC%9D%98%20%ED%95%9C%EB%A5%98[동아시아의 한류]
https://namu.wiki/w/%EC%9D%BC%EB%B3%B8%EC%9D%98%20%ED%95%9C%EB%A5%98[일본의 한류]

해당 저작물은 https://creativecommons.org/licenses/by-nc-sa/2.0/kr/[CC BY-NC-SA 2.0 KR]에 의해 사용됨.